In [1]:
import numpy as np

In [4]:
# scala
x = np.array(5)

print(x.ndim)
print(x.shape)
print(x.dtype)

0
()
int64


In [5]:
# vector
y = [1,2,3,4,5]
y = np.array(y)

print(y.ndim)
print(y.shape)
print(y.dtype)

1
(5,)
int64


In [6]:
x = np.array([ [[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [5,6,7,8]] ])

In [8]:
print(x)
print(x.ndim)
print(x.shape)
print(x.dtype)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
3
(2, 2, 4)
int64
