In [8]:
from keras import models
from keras import layers

model = models.Sequential()
model.add(layers.Dense(784, activation='relu', input_shape=(28 * 28, )))
model.add(layers.Dense(10, activation='softmax'))    # Classify 0 to 9

In [9]:
model.compile(optimizer='rmsprop',
                         loss='categorical_crossentropy',
                         metrics=['accuracy'])


In [10]:
from keras.datasets import mnist

(train_X, train_y_), (test_X, test_y_) = mnist.load_data()

In [11]:
print("\ntrain_X: =========")
print(train_X.shape)
print(train_X)

print("\ntrain_y_: ==========")
print(train_y_.shape)
print(train_y_)

print("\ntest_X: ===========")
print(test_X.shape)
print(test_X)

print("\ntest_y_: ==========")
print(test_y_.shape)
print(test_y_)


train_X: =========
(60000, 28, 28)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]

train_y_: ==========
(60000,)
[5 0 4 ... 5 6 8]

test_X: ===========
(10000, 28, 28)
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0

In [13]:
train_X = train_X.reshape((60000, 28 * 28))
train_X = train_X.astype('float32') / 255

test_X = test_X.reshape((10000, 28 * 28))
test_X = test_X.astype('float32') / 255


In [14]:
from keras.utils import to_categorical

train_y_ = to_categorical(train_y_)
test_y_ = to_categorical(test_y_)

In [15]:
model.fit(train_X, train_y_, epochs=5, batch_size=128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 10s 159us/step - loss: 1.3460 - acc: 0.7002
Epoch 2/5
60000/60000 [==============================] - 8s 139us/step - loss: 0.5082 - acc: 0.8683
Epoch 3/5
60000/60000 [==============================] - 10s 160us/step - loss: 0.3769 - acc: 0.89501s - lo
Epoch 4/5
60000/60000 [==============================] - 9s 143us/step - loss: 0.3323 - acc: 0.9048
Epoch 5/5
60000/60000 [==============================] - 8s 133us/step - loss: 0.3076 - acc: 0.9113


In [16]:
test_loss, test_acc = model.evaluate(test_X, test_y_)
print('test_acc: ', test_acc)

10000/10000 [==============================] - 1s 113us/step
test_acc:  0.9161
